network_config_map = {
    'MAINNET': {'NAME': 'MAIN', 'NB_FREEZE_CYCLE': 5, 'BLOCK_TIME_IN_SEC': 60, 'BLOCKS_PER_CYCLE': 4096},
    'ALPHANET': {'NAME': 'ALPHA', 'NB_FREEZE_CYCLE': 2, 'BLOCK_TIME_IN_SEC': 30, 'BLOCKS_PER_CYCLE': 2048},
    'ZERONET': {'NAME': 'ZERO', 'NB_FREEZE_CYCLE': 5, 'BLOCK_TIME_IN_SEC': 20, 'BLOCKS_PER_CYCLE': 128},
}
